# Generated by Django 2.2.4 on 2019-08-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particcipant_ID', models.CharField(max_length=10)),
                ('Barcode', models.IntegerField()),
                ('Week', models.IntegerField()),
                ('npa_a4_growth', models.CharField(max_length=10)),
                ('datecollection', models.DateField()),
                ('Presence_of_Pneumococcus', models.BooleanField(default=False)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=6)),
                ('HIVexposed', models.BooleanField()),
                ('site', models.CharField(max_length=100)),
                ('BCG_given_birth', models.BooleanField(default=False)),
                ('BCG_date_birth', models.DateField()),
                ('DTaP_given_610wk', models.BooleanField(default=False)),
                ('DTaP_date_610wk', models.DateField()),
                ('PCV_given_610wk', models.BooleanField(default=False)),
                ('PCV_date_610wk', models.DateField()),
                ('DTaP_given_10wk', models.BooleanField(default=False)),
                ('DTaP_date_10wk', models.DateField()),
                ('DTaP_given_14wk', models.BooleanField(default=False)),
                ('DTaP_date_14wk', models.DateField()),
                ('PCV_given_14wk', models.BooleanField(default=False)),
                ('PCV_date_14wk', models.DateField()),
                ('PCV_given_9m', models.BooleanField(default=False)),
                ('PCV_date_9m', models.DateField()),
                ('Disease', models.BooleanField(default=False)),
                ('Serotype_autocolour', models.CharField(max_length=5)),
                ('vaccine_status_autocolour', models.CharField(max_length=5)),
                ('Sequence_Type', models.CharField(max_length=10)),
            ],
        ),
    ]
