# Generated by Django 2.2.4 on 2019-08-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swab',
            name='id',
        ),
        migrations.AlterField(
            model_name='swab',
            name='Barcode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
