# Generated by Django 2.2.4 on 2019-08-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabs', '0003_auto_20190823_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swab',
            name='Disease',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='HIVexposed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='Presence_of_Pneumococcus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='Sequence_Type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='Serotype_autocolour',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='vaccine_status_autocolour',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
