# Generated by Django 2.2.4 on 2019-08-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabs', '0004_auto_20190823_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swab',
            name='Barcode',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
