# Generated by Django 2.2.4 on 2019-08-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabs', '0005_auto_20190823_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swab',
            name='BCG_date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='BCG_given_birth',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='DTaP_date_10wk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='DTaP_date_14wk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='DTaP_date_610wk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='DTaP_given_10wk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='DTaP_given_14wk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='PCV_date_14wk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='PCV_date_610wk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='PCV_date_9m',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='PCV_given_14wk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='PCV_given_9m',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
