# Generated by Django 2.2.4 on 2019-08-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabs', '0006_auto_20190823_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swab',
            name='DTaP_given_610wk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='PCV_given_610wk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='swab',
            name='Serotype_autocolour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
