# Generated by Django 2.2.4 on 2019-08-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabs', '0007_auto_20190823_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swab',
            name='Serotype_autocolour',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
