# Generated by Django 2.2.4 on 2019-08-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabs', '0008_auto_20190823_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swab',
            name='npa_a4_growth',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
