# Generated by Django 2.2.4 on 2019-08-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabs', '0009_auto_20190823_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='swab',
            name='BenzeneCat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='BenzeneCat_post',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='CO_Broad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='CO_Broad_post',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='CO_Strict',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='CO_Strict_post',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='Coal_stove',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='HHdsize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='HomeType',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='NO2Cat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='NO2Cat_Post',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='Paraffin_stove',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='SO2Cat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='SO2Cat_Post',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='TolueneCat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='TolueneCat_post',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='antibio_use_1yr',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='education',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='geo_lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='geo_long',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='mother_smoke_anytime',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='total_smokers_anytime',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swab',
            name='weight_birth',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
    ]
