# Generated by Django 2.2.4 on 2019-08-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabs', '0010_auto_20190827_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swab',
            name='Week',
            field=models.FloatField(),
        ),
    ]
