# Generated by Django 2.2.4 on 2019-08-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabs', '0014_auto_20190827_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swab',
            name='Week',
            field=models.IntegerField(),
        ),
    ]
