# Generated by Django 2.2.4 on 2019-08-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabs', '0016_auto_20190828_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swab',
            name='BCG_given_birth',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='swab',
            name='DTaP_given_10wk',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='swab',
            name='DTaP_given_14wk',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='swab',
            name='Disease',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='swab',
            name='HIVexposed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='swab',
            name='PCV_given_14wk',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='swab',
            name='PCV_given_610wk',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='swab',
            name='PCV_given_9m',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='swab',
            name='antibio_use_1yr',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='swab',
            name='mother_smoke_anytime',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
