# Generated by Django 2.2.4 on 2019-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabs', '0017_auto_20190828_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swab',
            name='Presence_of_Pneumococcus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
